# for scrutinizer-ci
filter:
    excluded_paths: [tests/*]

checks:
    php: true

tools:
    external_code_coverage:
        timeout: 600
        runs: 3
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [tests]
    php_cpd:
        enabled: true
        excluded_dirs: [tests]
