# for travis-ci
language: php

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  directories:
        - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
  include:
    - php: 5.5
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/php-cs-fixer fix --config-file=".php_cs" --dry-run
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
